environments:
  benrd:
  bingrd:
  dev:
  prod-blue:
  prod-green:
  prototype:


releases:

  - name: oasubapi-{{ requiredEnv "BRANCH" }}
    chart: ../helm/charts/oas-unblock-bot-bdm-dev
    namespace: oas-ub-{{ requiredEnv "BRANCH" }}
    values:
      - overrides/oas-unblock-bot-bdm-dev-api.yaml.gotmpl
    labels:
        category: prototype
        app: oas-unblock-bot-bdm-dev
        tier: api
    wait: false
    installed: true
    force: false