version: '3.7'

services:

  application:
    image: ${PROJECT}:${GIT_LOCAL_BRANCH}
    container_name: ${PROJECT}
    env_file: ./src/.env
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      TZ: ${TZ}
      MICROSOFT_APP_ID: ${MICROSOFT_APP_ID}
      MICROSOFT_APP_PASSWORD: ${MICROSOFT_APP_PASSWORD}
    ports:
      - "3978:3978"
    volumes:
      # Binds the application folder from the host inside the container for fast changes
      # - .:/usr/src/app
      # Ignores/Hides the node_modules from the bind on the host allowing the node_modules
      # from inside the container to be used instead
      - /usr/src/app/node_modules
    networks:
      - backend

networks:
  backend:
    name: "common-backend"
    driver: "bridge"

